### ISSUE TITLE
AttributeError: module 'simplejson' has no attribute 'loads' 

### ISSUE THREAD

**Issue by Cantalou15** [azarz/road2qgis#1]
Test du plugin sur QGIS 3.28

Le calcul d'itinéraire ne fonctionne pas.

QGis renvoi l'erreur suivante : 

Une erreur est survenue lors de l'éxécution du code Python: 

AttributeError: module 'simplejson' has no attribute 'loads' 
Traceback (most recent call last):
  File "C:\Users/suco80d/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\road2qgis\ui\road2qgis_dialog.py", line 157, in compute_route
    resp = req.doRequest()
  File "C:\Users/suco80d/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\road2qgis\core\road2_request.py", line 87, in doRequest
    return Road2Response(req.json())
  File "C:\QGIS\apps\Python39\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
AttributeError: module 'simplejson' has no attribute 'loads'

**Comment by azarz** [comment]
Je ne reproduis pas sur avec QGIS 3.28 sur mon installation d'Ubuntu.

Le problème semble venir d'un problème de nommage de conflits entres les librairies `json` et `simplejson`.

J'ai créé une branche qui tente de régler le problème sur votre installation, pouvez-vous me dire si ça fonctionne ?
https://github.com/azarz/road2qgis/tree/fix/simplejson_has_no_attribute_loads

**Comment by Cantalou15** [comment]
Désolé: je viens rarement sur Github...
Je viens de faire un test du plugin sur QGis 3.30.2 : ça fonctionne ! 

Merci
